### PR TITLE
Ajitava edited articles no common url param

### PR DESCRIPTION
**Pull request by ajitava-git**
**Task**:

Verify that articles that have been edited do not have common tracking URL parameters.

**Steps**:
1. Created test suite - newsletter_no_common_url_param_articles_expectation_suite.json
2. Used newsletter_automation.article table as a data source
3. Query used in runtime_parameters and saved in tracking_url_param_validation.yml:
SELECT * from newsletter_automation.articles WHERE title !="" and description !="" and time !=""
4. Expectation used to make sure the edited articles do not have common tracking URL parameters: 
expect_column_values_to_be_unique
5. Python script for the checkpoint - test_tracking_url_param_validation.py

### CODE REVIEW

**Comment by PreedhiVivek** [comment]
@ajitava-git , 
- Please merge your code with the latest master. great_expectations yml will not need any update. You could check the latest master.
- File names are too long. Can be made crispier say 'url_parameter_validation'. Refer to the naming of the expectation, checkpoint, test file name in the master branch
- I believe, along with filtering on title, description and time, newsletter_id being null would help pull only those records which have not been used up so far

**Comment by PreedhiVivek** [comment]
@ajitava-git ,
- Please ensure you run and verify your test before raising PR.
- The expectation_suite_name mismatches between your checkpoint and expectation.
- Checkpoint needs to have only your batch_request for validation. It at the moment has three others. Please update. 
- No updates are required to great_expectation yml. DevOps has done the required updates in the Main branch.

**Comment by shivahari** [comment]
@ajitava-git Where you able to run the `checkpoint` locally?

I have hit `expectation_suite newsletter_test_url_param_expectation_suite not found` error.

**Comment by qxf2** [comment]
@ajitava-git - can you please check to see where this PR stands? I am cleaning out our repos to have fewer stale branches/PRs.

**Comment by ajitava-git** [comment]
@qxf2 Sure. I think this should be resolved. I missed updating the conversation me and shiva had over skype for this. Post my last commits, Shiva was able to run the checkpoint.

**Pull request merged**
